# Vectorization
Vectorization allows you to perform operations on entire arrays at once, instead of iterating over elements one by one. This is made possible by NumPy’s optimized C-based backend that executes operations in compiled code, which is much faster than Python loops.

Vectorized operations are also more readable and compact, making your code easier to maintain.

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
squared_arr= arr**2 #Vectorized operation
squared_arr

array([ 1,  4,  9, 16, 25, 36])

# Broadcasting: Scaling Arrays Without Extra Memory

Broadcasting is a powerful feature of NumPy that allows you to perform operations on arrays of different shapes without creating copies. It “stretches” smaller arrays across larger arrays in a memory-efficient way, avoiding the overhead of creating multiple copies of data.

In [2]:
arr = np.array([1, 2, 3, 4, 5])
result= arr+10 #Broadcasting: 10 is added to all the elements of array.
result

array([11, 12, 13, 14, 15])

In [3]:
arr1 = np.array([1, 2,3])
arr2 = np.array([10, 20, 30])

result = arr1 + arr2  # Element-wise addition
print(result)  # Output: [11 22 33]

[11 22 33]


In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[10, 20, 30], [12,34,61]])

result = arr1 + arr2  # Here, arr1 is broadcast across rows of arr2, adding [1,2,3] to each row.
print(result)  

[[11 22 33]
 [13 36 64]]


In [5]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


* Vectorization = Do the same operation on every element without writing a loop.
* Broadcasting = Make arrays of different shapes work together automatically.