In [1]:
import numpy as np

In [2]:
arr1=np.array([2,3,4,7]) # 1-D Array
arr2=np.array([[1,2,3],[5,6,4],[9,4,2]]) # 2-D Array

In [3]:
print(arr1)
print(arr2)

[2 3 4 7]
[[1 2 3]
 [5 6 4]
 [9 4 2]]


In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.full((4,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [8]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [9]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [10]:
print(arr2.shape)

(3, 3)


In [11]:
print(arr2.size)

9


In [12]:
print(arr2.ndim)

2


In [13]:
print(arr2.dtype)

int64


In [14]:
arr = np.array([1, 2, 3], dtype=np.float64)  # Explicit type
print(arr.dtype)  # float64
print(arr)

float64
[1. 2. 3.]


In [15]:
arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]

[1 2 3]


In [16]:
arr=np.array([[3,4,5,6],[1,3,4,6],[2,34,5,6]])
arr

array([[ 3,  4,  5,  6],
       [ 1,  3,  4,  6],
       [ 2, 34,  5,  6]])

In [17]:
arr.shape

(3, 4)

In [18]:
reshaped=arr.reshape((4,3))
reshaped

array([[ 3,  4,  5],
       [ 6,  1,  3],
       [ 4,  6,  2],
       [34,  5,  6]])

In [19]:
arr.reshape((6,2))

array([[ 3,  4],
       [ 5,  6],
       [ 1,  3],
       [ 4,  6],
       [ 2, 34],
       [ 5,  6]])

In [20]:
flattened=arr.flatten()
flattened

array([ 3,  4,  5,  6,  1,  3,  4,  6,  2, 34,  5,  6])

In [21]:
arr

array([[ 3,  4,  5,  6],
       [ 1,  3,  4,  6],
       [ 2, 34,  5,  6]])