In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
flat=arr.flatten()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [2]:
flat[3:12]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
flat[::2]

array([ 1,  3,  5,  7,  9, 11])

In [4]:
sliced=flat[0:6]
sliced

array([1, 2, 3, 4, 5, 6])

In [5]:
sliced[0]=10

In [6]:
sliced

array([10,  2,  3,  4,  5,  6])

In [7]:
flat

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
copied_scile=sliced[0:6].copy()
copied_scile[0]=100
copied_scile

array([100,   2,   3,   4,   5,   6])

In [9]:
sliced

array([10,  2,  3,  4,  5,  6])

In [10]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
idx = [1, 4, 7]  # Indices to select
print(arr[idx])  # [20 50 80]

[20 50 80]


In [11]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
mask= arr>=40
print([arr[mask]])

[array([40, 50, 60, 70, 80])]
