In [1]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
np.sum(arr, axis=0) # Moves downwards and collpse(sum) all the coloums.

array([12, 15, 18])

In [3]:
np.sum(arr,axis=1) # Moves horizontally and collapse(sum) all the rows.

array([ 6, 15, 24])

In [4]:
print(arr[1,1])

5


In [5]:
print(arr[0:3,1:3])

[[2 3]
 [5 6]
 [8 9]]


In [6]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
print(arr3D[1,1,0])

10


In [8]:
print(arr3D[1,1,])

[10 11 12]


In [9]:
print(arr3D[:,0,:])

[[1 2 3]
 [7 8 9]]


In [10]:
print(arr3D[:,:,0])

[[ 1  4]
 [ 7 10]]


In [11]:
print(arr[:,0])

[1 4 7]


In [12]:
arr[:,1] = 0
arr

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])