# Practice Questions

Q1. Create a 3×3 array filled with random numbers and print its shape.

In [1]:
import numpy as np

arr=np.array([[2,4,5],[23,4,8],[0,18,1]])
arr.shape

(3, 3)

Q2. Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [2]:
arr=np.array([1.1,2.2,3.3])
arr

array([1.1, 2.2, 3.3])

In [3]:
int_arr=arr.astype(np.int64)
int_arr

array([1, 2, 3])

Q3. Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [4]:
arr=np.array([1,2,3,4,5,6])
print(arr[[1,3,5]])


[2 4 6]


Q4. Reshape a 1D array of size 9 into a 3×3 matrix.

In [5]:
arr=np.array([[2,4,5],[23,4,8],[0,18,1]])
arr1=arr.flatten()
print(arr1.size)
print(arr1)

9
[ 2  4  5 23  4  8  0 18  1]


In [6]:
reshaped=arr1.reshape((3,3))
reshaped

array([[ 2,  4,  5],
       [23,  4,  8],
       [ 0, 18,  1]])

Q5. Use boolean masking to filter numbers greater than 50 in an array.

In [7]:
arr=np.array([[91,4,55],[23,4,80],[0,18,100]])
mask=arr>50
arr[mask]

array([ 91,  55,  80, 100])