In [1]:
#Python Zip Explained.
l1=[2,4,1]
l2=[3,2,6]
list(zip(l1,l2))

[(2, 3), (4, 2), (1, 6)]

In [2]:
#Using Python List.
import sys
import numpy as np
import time

size=1_000_000_00
l1=list(range(size))
l2=list(range(size))

start=time.time()
add=[x+y for x,y in zip(l1,l2)]
end=time.time()
print(add[0:10])
print("Python list addition time: ",end - start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
Python list addition time:  4.779767751693726


In [3]:
total = sys.getsizeof(l1)

for item in l1:
    total += sys.getsizeof(item)
print("Python list size:", total, "bytes")

Python list size: 3600000056 bytes


In [4]:
#Using numpy Array.
import numpy as np
import time

size=1_000_000_00
l1=np.array(l1)
l2=np.array(l2)

start=time.time()
add=l1+l2
end=time.time()
print(add[0:10])
print("Numpy array addition time: ",end - start)

[ 0  2  4  6  8 10 12 14 16 18]
Numpy array addition time:  1.565276861190796


In [5]:
print("NumPy array size:", l1.nbytes, "bytes")

NumPy array size: 800000000 bytes


In [6]:
#Creating a 1-D Array.
arr1=np.array([1,3,5,17])
arr1

array([ 1,  3,  5, 17])

In [7]:
#Creating a 2-D array.
arr2=np.array([[4,56,8], [3,5,9]])
arr2

array([[ 4, 56,  8],
       [ 3,  5,  9]])

In [8]:
print("Type: ", type(arr1))
print("Shape: ", arr2.shape) #Tells Rows and column in array.

Type:  <class 'numpy.ndarray'>
Shape:  (2, 3)


In [9]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)
total = sys.getsizeof(list_data)

for item in list_data:
    total += sys.getsizeof(item)
print("Python list size:", total, "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 36056 bytes
NumPy array size: 8000 bytes


In [10]:
# Python list (loop-based)
list1=[1,2,3,4]
start=time.time()
list_squares = [x ** 2 for x in list1]
end=time.time()
print("Time taken: ",end-start)
list_squares

Time taken:  6.532669067382812e-05


[1, 4, 9, 16]

In [11]:
# NumPy (vectorized)
start=time.time()
numpy_squares = arr1 ** 2
end=time.time()
print("Time taken: ",end-start)
numpy_squares

Time taken:  5.2928924560546875e-05


array([  1,   9,  25, 289])